version: "3.7"

services:
  web-api:
    build:
      context: ..
      dockerfile: WebAPI/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80;https://+:443
      - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
      - ASPNETCORE_Kestrel__Certificates__Default__Password=1234
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - $USERPROFILE\.aspnet\https:/https/